name: demo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
   
  geocoding: ^2.1.1 
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.2

  # Maps (existing OSM stack)
  flutter_map: ^8.2.1
  latlong2: ^0.9.0

  # Google Maps (for Safety Navigator page)
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.9

  # Search autocomplete (NEW)
  flutter_typeahead: ^5.2.0

  # Permissions / location / storage
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
