import 'package:hive/hive.dart';

part 'hex_zone_model.g.dart'; // generated by build_runner

@HiveType(typeId: 0)
class HexZone extends HiveObject {
  @HiveField(0)
  String zoneId;

  /// Polygon boundary as [[lat, lng], ...]
  @HiveField(1)
  List<List<double>> boundary;

  /// ARGB color (e.g., 0xFF00FF00)
  @HiveField(2)
  int colorValue;

  /// Latest severity score
  @HiveField(3)
  double score;

  /// City/district this hex belongs to
  @HiveField(4)
  String city;

  /// When we last updated this item
  @HiveField(5)
  DateTime updatedAt;

  /// Tile index for lazy loading (e.g. "33.8_35.5")
  @HiveField(6)
  String tileId;

  HexZone({
    required this.zoneId,
    required this.boundary,
    required this.colorValue,
    this.score = 0.0,
    this.city = "",
    DateTime? updatedAt,
    this.tileId = "",
  }) : updatedAt = updatedAt ?? DateTime.now();
}